# Generated by Django 4.0.1 on 2022-06-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_bid',
            field=models.DecimalField(decimal_places=3, default=0.001, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
