# Generated by Django 4.0.1 on 2022-06-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_bidder_bid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_bid',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
