# Generated by Django 4.0.1 on 2022-06-23 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_watchlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
